import Head from 'next/head'
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillGithub,
  AiFillLinkedin,
  AiFillMessage,
} from "react-icons/ai";
import nathan from "../styles/assets/nathan.jpeg"
import Image from "next/legacy/image";
import soft from "../styles/assets/soft.png";
import react from "../styles/assets/react.png";
import language from "../styles/assets/language.jpg"
import { useState } from 'react';
import booki from "../styles/assets/booki.png"
import panthere from "../styles/assets/panthère.png"
import kanap from "../styles/assets/kanap.png"
import piquante from "../styles/assets/piquante.png"
import kasa from "../styles/assets/kasa.png"
import portfolio from "../styles/assets/portfolio.png"
import student from "../styles/assets/student-portfolio.png"



export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Casciano Nathan Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="../styles/assets/favicon.ico" />
      </Head>
      <main className=' bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40'>
        <section className=' min-h-screen' >
         <nav className=' py-10 mb-12 flex justify-between'>
          <h1 className='  text-sm my-3 font-burtons'>Portfolio</h1>
           <ul className=' flex items-center'>
            <li><BsFillMoonStarsFill
            onClick={() => setDarkMode (!darkMode)}
             className=' cursor-pointer text-1xl' />
            </li>
            <li>
              <a className='bg-gradient-to-r from-green-500 text- to-teal-500 text-white px-2 py-1 border-none rounded-md ml-8' 
            href='#'> Click to the moon ! </a></li>
           </ul>


         </nav>
         <div className=' text-center p-10 py-10'>
          <h2 className=' text-5xl py-2 text-green-500 font-medium dark:text-green-400 md:text-6xl'>Casciano Nathan</h2>
          <h3 className=' text-2xl py-2 dark:text-white md:text-3xl'>Developpeur Front-End</h3>
          <p className=' text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl'>En activité depuis 1 an</p>
         </div>
         <div  className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
               <a href='https://github.com/NathanCso'>
              <AiFillGithub /> </a>
              <a href='https://www.linkedin.com/in/nathan-casciano-606923232/'> 
              <AiFillLinkedin /> </a>
              <a href='mailto:ncprograndest@gmail.com'>
              <AiFillMessage/> </a>
         </div>
         <div className="mx-auto bg-gradient-to-b from-gray-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
         <Image src={nathan} layout="fill" objectFit="cover" />
         </div>
        </section>
        <section>
          <div>
          <h3 className="text-3xl py-1 dark:text-white ">Je me présente....</h3>
          <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
          Développeur web spécialisé dans le <span className="text-green-500"> Front-End </span> avec un véritable attrait pour le design . Je suis désireux d'apprendre toujours plus et je considère que chaque projet permet d'acquérir de nouvelles <span className="text-green-500">compétences</span>, j'ai eu l'occasion durant mon parcours de formation de réaliser plusieurs projets en mettant en oeuvre différentes techniques et différentes <span className="text-green-500">technologies</span>. Grâce à mes multiples expériences professionnelles dans des domaines variés je saurais faire preuve <span className="text-green-500">d'adaptabilité et de professionnalisme</span>
          </p>
          <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Voyons ce que j'ai eu l'occasion d'apprendre durant mon parcours !
            </p>
          </div>
          <div className=' lg:flex gap-10'> 
            {/* Carte Design */}
            <div className=' text-center  shadow-lg  p-10 rounded-xl my-10 dark:bg-white flex-1 '>
            <Image src={react} width={100} height={100}/>
            <h3 className="text-lg font-medium pt-8 pb-2  ">
                Languages et Frameworks
              </h3>
              <p className="py-2"> J'ai pu découvrir et utiliser ces outils dans différents projets 
              </p>
              <h4 className=" text-3xl text-green-500 ">↓</h4>
              <p className="text-gray-800 py-1">JavaScript</p>
              <p className="text-gray-800 py-1">React</p>
              <p className="text-gray-800 py-1">NodeJs</p>
              <p className="text-gray-800 py-1">Express</p>
              <p className="text-gray-800 py-1">Tailwind CSS</p>
              <p className="text-gray-800 py-1">NextJs</p>
              <p className="text-gray-800 py-1">Bootstrap</p>
              <p className="text-gray-800 py-1">HTML/CSS</p>
            </div>
            {/* Carte différn */}
            <div className=' text-center  shadow-lg  p-10 rounded-xl my-10 dark:bg-white flex-1'>
            <Image src={language} width={100} height={100}/>
            <h3 className="text-lg font-medium pt-8 pb-2  ">
                Outils et environnements  
              </h3>
              <p className="py-2">
                Environnements de travail que j'ai l'habitude ou la préférence d'utiliser 
              </p>
              <h4 className=" text-3xl text-green-500 ">↓</h4>
              <p className="text-gray-800 py-1">Je travaille essentiellement sur Windows mais je suis capable d'adaptation</p>
              <p className="text-gray-800 py-1">Utilisation de Git , GitHub et GitHub Browserr</p>
              <p className="text-gray-800 py-1">Connaissance de Visual Studio Code et ses extensions</p>
              <p className="text-gray-800 py-1">Utilisation de Figma</p>
            </div>
            {/* Carte Code */}
            <div className=' text-center  shadow-lg  p-10 rounded-xl my-10 dark:bg-white flex-1'>
            <Image src={soft} width={100} height={100}/>
            <h3 className="text-lg font-medium pt-8 pb-2  ">
                Soft Skills
              </h3>
              <p className="py-2">
                Qualités humaines et sociales dont je sais faire preuve 
              </p>
              <h4 className=" text-3xl text-green-500 ">↓</h4>
              <p className="text-gray-800 py-1">Gestion du temps</p>
              <p className="text-gray-800 py-1">Travail Collaboratif</p>
              <p className="text-gray-800 py-1">Patience et Calme</p>
              <p className="text-gray-800 py-1">Adaptabilité</p>
              <p className="text-gray-800 py-1">Sens des résponsabilités</p>
            </div>
          </div>
        </section>
        <section>
          <div>
          <h3 className="text-3xl py-1 dark:text-white ">Mes projets</h3>
          <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Voici les différents projets que j'ai pu effectués , pour le moment beaucoup sont issus de ma formation de 
              <span className="text-teal-500"> Développeur Web chez OpenClassrooms</span>
              <span className=' mx-1'>néanmoins de nouveaux projets sont en cours de réalisation.</span>
              </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            Certains projets sont visitables directement pour les autres vous serez redirigé sur ma page <span className="text-teal-500">GitHub </span>
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <a className='' href='https://taupe-starburst-904973.netlify.app/'>
              <Image
                className=" hover:scale-75 rounded-lg object-cover"
                width={"90%"}
                height={"60%"}
                layout="responsive"
                src={booki}
              />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a href='https://nathancso.github.io/P4-SEO-La-panthere/'>
              <Image
                className="rounded-lg object-cover hover:scale-75"
                width={"90%"}
                height={"60%"}
                layout="responsive"
                src={panthere}
              />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a href='https://github.com/NathanCso/P5-Kanap'> 
              <Image
                className="rounded-lg object-cover hover:scale-75"
                width={"90%"}
                height={"60%"}
                layout="responsive"
                src={kanap}
              />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a href='https://github.com/NathanCso/P6-API-Hot-Takes'>
              <Image
                className="rounded-lg object-cover hover:scale-75"
                width={"90%"}
                height={"60%"}
                layout="responsive"
                src={piquante}
              />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a href='https://github.com/NathanCso/P7-React-Kasa/tree/main/kasa'>
              <Image
                className="rounded-lg object-cover hover:scale-75"
                width={"90%"}
                height={"60%"}
                layout="responsive"
                src={kasa}
              />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a href='https://famous-narwhal-b433da.netlify.app/'>
              <Image
                className="rounded-lg object-cover hover:scale-75"
                width={"90%"}
                height={"60%"}
                layout="responsive"
                src={portfolio}
              />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a href='https://poetic-paprenjak-ab04c9.netlify.app/'>
              <Image
                className="rounded-lg object-cover hover:scale-75"
                width={"90%"}
                height={"60%"}
                layout="responsive"
                src={student}
              />
              </a>
            </div>
          </div>
        </section>
      </main>
        </div>
  )
}
